### ISSUE TITLE
sort order and stating open source choice

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintdrivers#1]
Was reading the April 2013 monthly news blog post which talked about mintdrivers and wanted to suggest a re-ordering of the driver list and a clear stating of the open source choice, as the recommended choice will normally be the closed source driver. Below is my thoughts to the changes related to < http://www.linuxmint.com/tmp/blog/2358/thumb_mintdrivers.png >.

xserver-xorg-video-nouveau (open source)
nvidia-current (recommended)
nvidia-current-updates
nvidia-experimental-310
nvidia-experimental-304

or

nvidia-current (recommended)
nvidia-current-updates
xserver-xorg-video-nouveau (open source)
nvidia-experimental-310
nvidia-experimental-304

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintdrivers/commit/389315d52910680b7b861cc3f0971a095527db7f
