### ISSUE TITLE
detect.system_device_drivers() takes a long time.

### ISSUE THREAD

**Issue by jbruggeman** [linuxmint/mintdrivers#15]
detect.system_device_drivers() takes a very long time. While this isn't something that can be directly fixed, it's frustrating to open the app and wait for 10s until the window posts. Perhaps the UI can be tweaked to post and show loading while this code is executing so the user doesn't wind up with 2-3 windows because they're impatient.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintdrivers/commit/bd6286192f55267703e55a3cd33314dfe4ab5a0d
