### ISSUE TITLE
flgrx driver offered by driver-manager cannot be installed because of package system state

### ISSUE THREAD

**Issue by Eirikur** [linuxmint/mintdrivers#17]
flgrx is offered by driver-manager for my Radeon HD5450.  If selected, it tries to install it but fails because of held packages.  driver-manager should probably not offer packages that the package system will not allow to be installed.  Even better would be to address the package situation.  This is seen on a 17.1 standard install.

**Comment by clefebvre** [comment]
Fixed by http://git.io/v8Wjh
