### ISSUE TITLE
Shell Injection with a fake live usb

### ISSUE THREAD

**Issue by TheRegRunner** [linuxmint/mintdrivers#18]
https://bugs.launchpad.net/linuxmint/+bug/1502498

A command will run as root and disable the ufw firewall if you create this hidden folder and file on the usb stick :

/media/theregrunner/USB-STICK/test/.";sudo ufw disable;#"/README.diskdefines

![screenshot](https://cloud.githubusercontent.com/assets/13422603/10264895/ebbd5374-6a1a-11e5-8f66-b9759ebe28cc.png)

**Comment by TheRegRunner** [comment]
Patch
https://launchpadlibrarian.net/222747789/patch.diff

**Comment by TheRegRunner** [comment]
Better patch

https://launchpadlibrarian.net/222782485/patch2.diff

**Comment by LinuxOnTheDesktop** [comment]
I _presume_ that this security issue has been resolved . .

**Comment by clefebvre** [comment]
Indeed, it was fixed 5 years ago https://github.com/linuxmint/mintdrivers/commit/c9aaf715fff9e041abf132c163f80aa799931b55
