### ISSUE TITLE
list driver version update below main driver

### ISSUE THREAD

**Issue by philipzae** [linuxmint/mintdrivers#19]
One of the suggested improvements in the sorting of the list of drivers in issue #1 that may have been overlooked was to have driver updates located underneath the main driver.

When looking at the new image in the 17.3 release notes < http://www.linuxmint.com/pictures/screenshots/rosa/mintdrivers.png >, having the nvidia-346-updates driver located at the bottom rather than just underneath nvidia-346 makes it more difficult to browse through the list. This also goes for the 304-update appearing before the 304 which is computer sort friendly and not human sort friendly.

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintdrivers/commit/dbc2df367bab4fdcb563fc531bfc8623936bec7e
