### ISSUE TITLE
NVIDIA drivers from Ubuntu PPA shown as open source

### ISSUE THREAD

**Issue by rkingsbury** [linuxmint/mintdrivers#23]
I have the [Ubuntu NVIDIA driver PPA ](https://launchpad.net/~graphics-drivers/+archive/ubuntu/ppa)enabled in order to install the latest proprietary drivers. 

All the available drivers from the PPA show up in the driver manager, but they are all listed as "open source" which of course isn't true. The proprietary driver from the main repo doesn't say anything next to, while nouveau also has the open source label.

It also isn't very clear which drivers are provided by the PPA vs. which are coming from the main repos, although that may not be something that mintdrivers is intended to communicate.

**Comment by fizzgigfuzzlehead** [comment]
Same problem here.

**Comment by rkingsbury** [comment]
This is still happening in

![screenshot from 2016-06-13 08-08-34](https://cloud.githubusercontent.com/assets/1908695/16007028/38b67af8-313e-11e6-8485-7cab573b6735.png)
 the Mint 18 Beta
