### ISSUE TITLE
Driver manager silently fails after authentication

### ISSUE THREAD

**Issue by saildata** [linuxmint/mintdrivers#25]
I think this is related to #20

After entering valid credentials, the driver manager closes without an error notice or log entry. 

I manually ran ` sudo /usr/lib/linuxmint/mintDrivers/mintDrivers.py` and saw the error: 
```python
`Traceback (most recent call last):
  File "/usr/lib/linuxmint/mintDrivers/mintDrivers.py", line 10, in <module>
    from aptdaemon import client
ImportError: No module named 'aptdaemon'
```

Installing python3-aptdaemon.gtk3widgets seems to resolve the problem. :tada:

**Comment by javabrett** [comment]
Dependency likely added by bd6286192f55267703e55a3cd33314dfe4ab5a0d .
