### ISSUE TITLE
Add information about unknown device

### ISSUE THREAD

**Issue by Yaksinikos** [linuxmint/mintdrivers#35]
I've got today the new Driver Manager, and there is now a new Unknown Device listed.
It's the intel-microcode driver Version 3.20151106.1 for Processor microcode firmwar for Intel CPUs.
My CPU is ""LGA1366 Intel Core i7 X 980 6-Core 12x Threads (HTT)".
If there is more information required, I would open my PC and look up for more details.

By the way;
I've a lot of Hardware which is never listed in the system-information in Linux (while plugged in).
Where should I add the information, to get them in the next version of Linux listed?

**Comment by clefebvre** [comment]
Fixed by https://github.com/linuxmint/mintdrivers/commit/abcf03e5238fe9094c72e03740c0f8c6d035c4bc
