### ISSUE TITLE
Possibility installation codec to open encrypted dvds

### ISSUE THREAD

**Issue by pyroxar** [linuxmint/mintdrivers#37]
Linux Mint should have ption to easy installation codec to open encrypted dvds.
Good places are: mint-install when i install system on computer (checkbox near flash plugin and mp3 licenses) or mint-drivers when i install driver for my graphics card or something else hardware.
http://packages.ubuntu.com/xenial/libdvdcss2

What do you think?

**Comment by xenopeek** [comment]
During installation of Linux Mint the user can tick the box to install 3rd party software or after login the user can install Multimedia codecs from the Welcome Screen. Both options install this package as well.
