### ISSUE TITLE
Not resolving wifi driver dependencies

### ISSUE THREAD

**Issue by d-damien** [linuxmint/mintdrivers#40]
Hello there. After having tested LM 18.2 in liveUSB & checked everything worked, I installed it.

Alas ! Once installed, wifi did not work. So I ran `driver-manager`, which suggested I installed `bcmwl-kernel-source`. Unfortunately, it failed to resolve its dependencies in the USB key and tried to download them − which of course failed.

But it is possible ; here's what I had to do :

``` sh
# listing driver dependencies
apt-cache show bcmwl-kernel-source | grep Depends -m 1
Depends: dkms, linux-libc-dev, libc6-dev

# going to usb mounted folder
cd /your/usbkey/name

# finding driver
find . -iname "*bcmwl*"
./pool/main/b/bcmwl/bcmwl-kernel-source_6.30.223.271+bdcom-0ubuntu1~1.1_amd64.deb

# finding driver dependency n°1
find . -iname "*libc6-dev*"
./pool/main/g/glibc/libc6-dev_2.23-0ubuntu7_amd64.deb

# finding driver dep n°2
find . -iname "*libc-dev-bin*"
./pool/main/g/glibc/libc-dev-bin_2.23-0ubuntu7_amd64.deb

# copy & install them all
cp\
./pool/main/b/bcmwl/bcmwl-kernel-source_6.30.223.271+bdcom-0ubuntu1~1.1_amd64.deb\
./pool/main/g/glibc/libc6-dev_2.23-0ubuntu7_amd64.deb\
./pool/main/g/glibc/libc-dev-bin_2.23-0ubuntu7_amd64.deb\
.
dpkg -i *deb
```

This answer helped :
https://askubuntu.com/questions/55868/installing-broadcom-wireless-drivers

I guess this qualifies as bug. Could this be fixed in 18.2 (stable does not provide improvements but fixes bugs, right ?) ? I'd like to point out this could be disturbing for beginners, giving them hope for LM to work out of the box like in liveusb, and finally not.

**Comment by clefebvre** [comment]
I wonder if it's to do with a backport since the time of release.. 18.x is no longer available/supported.

This is actually one of the tests in our ISO QA, we always make sure this works. We test it on a Macbook Pro here with a broadcom chipset which requires these STA drivers.
