### ISSUE TITLE
Black screen after using the Driver Manager to install nvidia proprietary drivers twice in a row

### ISSUE THREAD

**Issue by Motherboard** [linuxmint/mintdrivers#46]
**What happened**

Using an nvidia card (Mine was 1080 ti, but I think others will do, as I've noticed there are several accounts of the black screen associated with nvidia going back several years ago).

I've installed the proprietary driver version 384 using Driver Manager, only to discover that I wanted a newer version. I then added the graphics-drivers ppa, and switched to 390 in the Driver Manager, and got a black screen.

I've then reinstalled the system, doing the exact same operations, apart from installing the 384 version first - and the system worked perfectly fine. So the problem seems to be that the Driver Manager didn't properly remove the previous version.

**What I'm expecting to happen**

The Driver Manager should have properly removed the previous version, or at least warn that these should be removed prior to installing the new ones.

**Steps to reproduce**

*   Install Linux Mint 18.3, select to install 3rd party packages during installation, default installation parameters.
*   Fully update the system, including upgrading to the 4.13 kernel
*   Restart
*   Open Driver Manager, select the 384 driver
*   Close Driver Manager
*   sudo add-apt-repository ppa:graphics-drivers/ppa && sudo apt update
*   Open Driver Manager, and select the 390 driver
*   Restart

**Comment by clefebvre** [comment]
This is no longer reproducible. However we think it's to do with the fact that APT recommends were not installed by default in Mint 18.3. This should no longer happen in modern releases.
