### ISSUE TITLE
Better driver for WiFi adapter

### ISSUE THREAD

**Issue by Knezev** [linuxmint/mintdrivers#47]
after installing Linux Mint, I have a problem with a wifi adapter, it does not work until I remove it and re-insert it into the enclosure. I managed to install it through the command
sudo apt-get install linux-headers-generic build-essential dkms
git clone https://github.com/pvaret/rtl8192cu-fixes.git
sudo dkms add ./rtl8192cu-fixes
sudo dkms install 8192cu/1.11
sudo depmod -a
sudo cp ./rtl8192cu-fixes/blacklist-native-rtl8192.conf /etc/modprobe.d/
sudo cp ./rtl8192cu-fixes/8192cu-disable-power-management.conf /etc/modprobe.d/
(it works great) :)

and I tried it across https://launchpad.net/~hanipouspilot/+archive/ubuntu/rtlwifi (work, but no good).

Could a new one be inserted driver for wifi adapter?

**Comment by xenopeek** [comment]
mintdrivers is the manager program, that discovers what drivers from the repositories are suitable for your system. It does not provide drivers nor does Linux Mint package hardware drivers.

What you linked to on GitHub notes the driver is deprecated and that in general the default driver from Linux kernel version 4.4 and up works well. Depending on your Linux Mint version you may have an older kernel version? Suggest to try the newest kernel version available for your Linux Mint version. For further help with your wifi issue you can use the [forums](https://forums.linuxmint.com/viewforum.php?f=53).
