### ISSUE TITLE
"Check your video drivers" keeps appearing on boot.

### ISSUE THREAD

**Issue by CTimmerman** [linuxmint/mintdrivers#62]
I'm running the latest updated Mint Cinnamon release and the "Check your video drivers" popup keeps appearing on boot, maybe because it can't find anything for my VirtualBox GPU, but there should be a way to dismiss Driver Manager's popup permanently.

**Comment by CTimmerman** [comment]
Checking the "Enable 3D acceleration" box in "VirtualBox Machine Settings, Display" got rid of it.

**Comment by JeffLabonte** [comment]
@CTimmerman I assume it was a Virtualbox issue rather than a mintdrivers? Should this issue be closed?

**Comment by CTimmerman** [comment]
I guess, as all GPUs have 3D acceleration now.
