### ISSUE TITLE
Java / GTK has problem with buttons

### ISSUE THREAD

**Issue by Win32netsky** [linuxmint/mintdrivers#64]
Hello
In 20.1 Mint is problem with buttons in java / gtk ?
Programm can not see buttons text, 
My ppa hibiscus-ppa is version jameica 2.8.6 ok the new version 2.10 ist not ok.
programm.
I can not new update for ppa make, test is not ok.
view:
https://www.dropbox.com/s/euv7ub4a1qedb6l/Schaltfl%C3%A4che.png?dl=0

**Comment by clefebvre** [comment]
Not related to mintdrivers.
