### ISSUE TITLE
Issue with kernel 5.12 and nvidia?

### ISSUE THREAD

**Issue by larsmartin4** [linuxmint/mintdrivers#65]
Hi i have issue with driver-manager (mindrivers) with 20.1 cinamon.
I use kernel mainline kernel installer 1.0.12 and did not get any warning that if you upgrade kernel its did not works nvidia drivers. Version 18.9.1 have removed support of kernel 5.12 on 20.04 and mint. Because of it.

Its works nice with ubuntu 21.04 so can you upgrade you program to support kernel 5.12?

Post-install mode detected
Checking Internet connectivity...
  --> Internet connection detected.
WARNING:root:_pkg_get_support nvidia-driver-390: package has invalid Support Legacyheader, cannot determine support level
Ignoring server NVIDIA driver:  nvidia-driver-418-server
Ignoring server NVIDIA driver:  nvidia-driver-450-server
Ignoring server NVIDIA driver:  nvidia-driver-460-server

Its missing supported kernel ubuntu 21.04 have:
software-properties-gtk --open-tab=4
WARNING:root:_pkg_get_support nvidia-driver-390: package has invalid Support Legacyheader, cannot determine support level
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.9.12-050912' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.9.12-050912' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.9.12-050912' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.1.0-050100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.0-051100' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.11.11-051111' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.9.12-050912' has bad syntax: version number does not start with a digit
dpkg: warning: version 'unsigned-5.12.0-051200' has bad syntax: version number does not start with a digit

**Comment by larsmartin4** [comment]
did anyone know? kernel and nvidia did not support or need later ubuntu?

**Comment by larsmartin4** [comment]
![nvidiaissue](https://user-images.githubusercontent.com/50201527/159136396-459e9417-bca3-4638-a7a8-4d5a0afa3c9f.png)
![ubuntu mainline kernel](https://user-images.githubusercontent.com/50201527/159136397-ea0a51b3-c250-45a0-981f-17023b6d16f4.png)
![laptop mint issue](https://user-images.githubusercontent.com/50201527/159136402-79a1c4d7-997d-492e-8489-094d02fe13e1.png)

**Comment by clefebvre** [comment]
I'm sorry, this isn't related to the driver manager itself. All it does is install/remove the drivers. Whether the drivers support your kernel series or not is handled upstream in Ubuntu and/or NVIDIA even.
