### ISSUE TITLE
Driver NVIDIA avec kernel 5.10.0-1057-oem

### ISSUE THREAD

**Issue by JeSuisEnPanne** [linuxmint/mintdrivers#71]
Hi, I'm using an nvidia graphics card.
LinuxMint offers me to install a version 510 or 470 driver.
When I do the install process it doesn't work.
I don't have linux-modules-nvidia version installed.
I can put my version of my kernel but I have an error message with linux-modules-nvidia-470-oem-20.04b-5.10.0-1057-oem 

linux-modules-nvidia-470-oem-20.04b:
Dépend : linux-modules-nvidia-470-5.10.0-1057-oem mais ne doit pas être installé
Dépend : nvidia-kernel-common-470 (<=470.86-1) mais 470.103.01-0ubuntu0.20.04.1 doit être installé

**Comment by clefebvre** [comment]
The -server pkgs are now filtered and no longer appear. They don't depend on nvidia-settings and nvidia-prime and aren't suitable here.

The rest seems to be related to a package conflict, that would have been upstream in Ubuntu. I can't reproduce this anymore unfortunately.
